"""link customer product and invoice#

Revision ID: 43e025f88dd6
Revises: 9ce0def73b09
Create Date: 2025-04-16 10:53:02.229030

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "43e025f88dd6"
down_revision: Union[str, None] = "9ce0def73b09"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("image_url", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "image_url")
    # ### end Alembic commands ###
