"""update customer

Revision ID: 473e84b6c8b9
Revises: c0bb07ec693a
Create Date: 2025-03-06 19:33:59.119144

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "473e84b6c8b9"
down_revision: Union[str, None] = "c0bb07ec693a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "customers", "name", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "customers", "email", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "users", "customer_uuid", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "customer_uuid", existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        "customers", "email", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "customers", "name", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
