"""link customer product and invoice

Revision ID: 7d78060e6773
Revises: 43e025f88dd6
Create Date: 2025-04-16 10:56:04.022132

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7d78060e6773"
down_revision: Union[str, None] = "43e025f88dd6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invoices",
        sa.Column("customer_product_uuid", sa.UUID(), nullable=False),
    )
    op.create_foreign_key(
        None,
        "invoices",
        "customer_products",
        ["customer_product_uuid"],
        ["uuid"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "invoices", type_="foreignkey")
    op.drop_column("invoices", "customer_product_uuid")
    # ### end Alembic commands ###
