"""update contract

Revision ID: c0bb07ec693a
Revises: 0ff98c538e4f
Create Date: 2025-03-06 14:51:15.756574

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c0bb07ec693a"
down_revision: Union[str, None] = "0ff98c538e4f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contracts", sa.Column("url", sa.String(), nullable=True))
    op.add_column(
        "customer_products",
        sa.Column("cancellation_date", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customer_products", "cancellation_date")
    op.drop_column("contracts", "url")
    # ### end Alembic commands ###
